# Copyright 2017-present SIGHUP s.r.l
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_name: gangway

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gangway
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    # ldflags:
    #   - >
    #     -s -w
    #     -X main.version={{.Version}}
    #     -X main.gitCommit={{.Commit}}
    #     -X main.buildTime={{.Date}}
    #     -X main.goVersion={{.Env.GO_VERSION}}
    #     -X main.osArch={{.Arch}}

archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-develop"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: sighupio
    name: gangway
  name_template: "{{ .Tag }}"
  prerelease: auto

dockers:
  - skip_push: auto
    image_templates:
      - "registry.sighup.io/gangway/gangway:latest"
      - "registry.sighup.io/gangway/gangway:v{{ .Major }}"
      - "registry.sighup.io/gangway/gangway:v{{ .Major }}.{{ .Minor }}"
      - "registry.sighup.io/gangway/gangway:{{ .Tag }}"
    dockerfile: ./Dockerfile
#
# docker_signs:
#   - artifacts: all
#     stdin: "{{ .Env.COSIGN_PWD }}"
#     args:
#       - "sign"
#       - "--key=env://COSIGN_KEY"
#       - "--upload=true"
#       - "--yes"
#       - "${artifact}"
