apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gangplank.fullname" . }}
  labels:
    {{- include "gangplank.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
