apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gangplank.fullname" . }}
  labels:
    {{- include "gangplank.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.sensitiveEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
