# Copyright 2017-present SIGHUP s.r.l
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

command:
  ["go", "run", "./cmd/gangplank", "-config", "/etc/gangplank/config.yaml"]

config:
  authorizeURL: http://localhost:5556/auth
  tokenURL: http://dex.dex:5556/token
  audience: http://dex.dex:5556/userinfo
  redirectURL: http://localhost:8080/callback
  usernameClaim: email
  clientID: gangplank
  clientSecret: gangplank
